title: GREWTCH
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io
logo: "/assets/images/GWR-Transparent-logo.png"
favicon_ico: "/assets/images/GWR-NoText - White.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
