title: GREWTCH
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs


logo: "/assets/images/GWR-Transparent-logo.png"
url: https://just-the-docs.github.io
favicon_ico: "/assets/images/GWR-Transparent-logo.ico"

footer_content: ""


